name: CMake CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Configure CMake
      run: cmake -B build -S .

    - name: Build
      run: cmake --build build --config Release

    - name: Run Tests
      working-directory: build
      run: ctest -C Release --output-on-failure